name: Build LXD images
on:
  push:
jobs:
  build:
    name: Build LXD images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install distrobuilder
        run: sudo snap install distrobuilder --classic

      - name: Install debootstrap
        run: sudo apt install -y debootstrap

      - name: Build image
        run: sudo distrobuilder build-lxd ubuntu.yml
