name: Build LXD images
on:
  push:
jobs:
  build:
    name: Build LXD images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install distrobuilder
        run: snap install distrobuilder --classic
